// Automatically generated by update_fantasy.py. Do not edit directly.
const fantasyData = {
  "last_updated": "2026-08-05 23:57:44",
  "latest_race": {
    "track": "Richmond Raceway",
    "date": "Aug 5, 2026",
    "caution_laps": 44,
    "winner": "Matt Crockett (118 pts)",
    "driver_scores": {
      "nick nickerson": {
        "driver_name": "nickerson, nick",
        "finish": 1,
        "start": 16,
        "incidents": 4,
        "status": "Running",
        "base_points": 40,
        "pole_bonus": 0,
        "most_laps_led_bonus": 5,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 45
      },
      "scott sanderson": {
        "driver_name": "sanderson, scott",
        "finish": 2,
        "start": 2,
        "incidents": 4,
        "status": "Running",
        "base_points": 35,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 35
      },
      "benjamin lacy": {
        "driver_name": "lacy, benjamin",
        "finish": 3,
        "start": 4,
        "incidents": 4,
        "status": "Running",
        "base_points": 34,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 34
      },
      "eddie hagigh": {
        "driver_name": "hagigh, eddie",
        "finish": 4,
        "start": 13,
        "incidents": 2,
        "status": "Running",
        "base_points": 33,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 33
      },
      "joshua adams": {
        "driver_name": "adams, joshua",
        "finish": 5,
        "start": 1,
        "incidents": 4,
        "status": "Running",
        "base_points": 32,
        "pole_bonus": 5,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 37
      },
      "connor gibson": {
        "driver_name": "gibson, connor",
        "finish": 6,
        "start": 8,
        "incidents": 2,
        "status": "Running",
        "base_points": 31,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 31
      },
      "jackson knaak": {
        "driver_name": "knaak, jackson",
        "finish": 7,
        "start": 5,
        "incidents": 10,
        "status": "Running",
        "base_points": 30,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 30
      },
      "kevin foster": {
        "driver_name": "foster, kevin",
        "finish": 8,
        "start": 7,
        "incidents": 12,
        "status": "Running",
        "base_points": 29,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 29
      },
      "johnathon platt": {
        "driver_name": "platt, johnathon",
        "finish": 9,
        "start": 14,
        "incidents": 20,
        "status": "Running",
        "base_points": 28,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 28
      },
      "ethan sikorski": {
        "driver_name": "sikorski, ethan",
        "finish": 10,
        "start": 10,
        "incidents": 16,
        "status": "Running",
        "base_points": 27,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 27
      },
      "matt crockett": {
        "driver_name": "crockett, matt",
        "finish": 11,
        "start": 15,
        "incidents": 4,
        "status": "Running",
        "base_points": 26,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 26
      },
      "michael rakes": {
        "driver_name": "rakes, michael",
        "finish": 12,
        "start": 11,
        "incidents": 14,
        "status": "Running",
        "base_points": 25,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 25
      },
      "davis carroll": {
        "driver_name": "carroll, davis",
        "finish": 13,
        "start": 19,
        "incidents": 12,
        "status": "Running",
        "base_points": 24,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 24
      },
      "ricky hart jr": {
        "driver_name": "hart jr, ricky",
        "finish": 14,
        "start": 18,
        "incidents": 8,
        "status": "Running",
        "base_points": 23,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 23
      },
      "adam tahan": {
        "driver_name": "tahan, adam",
        "finish": 15,
        "start": 26,
        "incidents": 18,
        "status": "Running",
        "base_points": 22,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 22
      },
      "garret bobo": {
        "driver_name": "bobo, garret",
        "finish": 16,
        "start": 3,
        "incidents": 4,
        "status": "Running",
        "base_points": 21,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 21
      },
      "victor weaver": {
        "driver_name": "weaver, victor",
        "finish": 17,
        "start": 20,
        "incidents": 12,
        "status": "Running",
        "base_points": 20,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 20
      },
      "logan murray": {
        "driver_name": "murray, logan",
        "finish": 18,
        "start": 12,
        "incidents": 8,
        "status": "Running",
        "base_points": 19,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 19
      },
      "bob berry": {
        "driver_name": "berry, bob",
        "finish": 19,
        "start": 21,
        "incidents": 4,
        "status": "Running",
        "base_points": 18,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 18
      },
      "nicole kriesel": {
        "driver_name": "kriesel, nicole",
        "finish": 20,
        "start": 25,
        "incidents": 0,
        "status": "Running",
        "base_points": 17,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 3,
        "dnf_penalty": 0,
        "total_points": 20
      },
      "ty corino": {
        "driver_name": "corino, ty",
        "finish": 21,
        "start": 23,
        "incidents": 16,
        "status": "Running",
        "base_points": 16,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 16
      },
      "ryan perrone": {
        "driver_name": "perrone, ryan",
        "finish": 22,
        "start": 24,
        "incidents": 6,
        "status": "Running",
        "base_points": 15,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 15
      },
      "bill harkins": {
        "driver_name": "harkins, bill",
        "finish": 23,
        "start": 17,
        "incidents": 1,
        "status": "Running",
        "base_points": 14,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 14
      },
      "dylan mcdonald": {
        "driver_name": "mcdonald3, dylan",
        "finish": 24,
        "start": 6,
        "incidents": 4,
        "status": "Running",
        "base_points": 13,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 13
      },
      "jackson duke": {
        "driver_name": "duke, jackson",
        "finish": 25,
        "start": 9,
        "incidents": 14,
        "status": "Running",
        "base_points": 12,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 12
      },
      "matthew bailey": {
        "driver_name": "bailey9, matthew",
        "finish": 26,
        "start": 27,
        "incidents": 10,
        "status": "Running",
        "base_points": 11,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 11
      },
      "tre ellis": {
        "driver_name": "ellis, tre",
        "finish": 27,
        "start": 22,
        "incidents": 2,
        "status": "Disconnected",
        "base_points": 10,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 10
      }
    }
  },
  "tiers": {
    "A": [
      "NICK NICKERSON",
      "JONATHON PLATT",
      "KEVIN FOSTER",
      "DAVID LEAKEY",
      "LOGAN MURRAY",
      "BENJAMIN LACY",
      "RICKY HART",
      "BRET GUZIK"
    ],
    "B": [
      "BILL HARKINS",
      "NICOLE KRIESEL",
      "SEAN BRITT",
      "JASON ALLEGRINI",
      "MATT CROCKETT",
      "JOSH ADAMS",
      "JOSHUA ADAMS",
      "MICHAEL RAMOS",
      "TY CORINO",
      "TYSON KOPF",
      "BOB BERRY",
      "JASON GREENWELL",
      "JOSH BILLITER",
      "JOSHUA BILLITER",
      "JACKSON KNAAK"
    ],
    "C": [
      "DIONTE RADER",
      "DIANTE RODER",
      "MATT BAILEY",
      "NATHAN SANTOS",
      "DYLAN NICASTRO",
      "ETHAN SIKORSKI",
      "REAGAN FRUGE",
      "CHAD HARTLE",
      "MICHAEL RAKES",
      "CURTIS YANCEY",
      "BRANDON GEERS",
      "MARK ALAN BIVENS",
      "DAVID WESTOVER JR",
      "BRANDON JACKSON",
      "EDDIE HAGIGH",
      "NOLAN GROSS",
      "DAVIS CARROLL",
      "LUCAS WILSON",
      "DYLAN MCDONALD",
      "WES FULLER",
      "RICKY GONZALES"
    ]
  },
  "recap_story": {
    "race_key": "Richmond Raceway (Aug 5, 2026)",
    "title": "Matt Crockett Wins at Richmond Raceway!",
    "date": "August 05, 2026",
    "content": "A fantastic week of racing at Richmond Raceway saw Matt Crockett claim the weekly fantasy victory with a score of 118 points! The race ran with 44 caution laps, which resolved any scoring ties using caution lap tiebreaker guesses. Check back soon for the full weekly results and roster breakdowns!"
  },
  "leaderboard": [
    {
      "name": "Bob Berry",
      "score": 588,
      "wins": 4,
      "wins_list": [
        "Atlanta",
        "Charlotte",
        "Bristol",
        "Pocono Raceway"
      ],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 101,
          "picks": [
            "BOB BERRY",
            "BENJAMIN LACY",
            "CONNOR GIBSON",
            "ETHAN SIKORSKI"
          ]
        },
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 121,
          "picks": [
            "BENJAMIN LACY",
            "JONATHON PLATT",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 126,
          "picks": [
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "BENJAMIN LACY",
            "BOB BERRY"
          ]
        },
        {
          "race": "Pocono Raceway (Jul 29, 2026)",
          "total": 126,
          "picks": [
            "ADAM TAHAN",
            "MICHAEL RAMOS",
            "SCOTT SANDERSON",
            "NICK NICKERSON"
          ]
        },
        {
          "race": "Richmond Raceway (Aug 5, 2026)",
          "total": 114,
          "picks": [
            "ADAM TAHAN",
            "JONATHON PLATT",
            "SCOTT SANDERSON",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 1
    },
    {
      "name": "Rebekah Weaver",
      "score": 549,
      "wins": 1,
      "wins_list": [
        "Atlanta"
      ],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 101,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 120,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 96,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Nashville Superspeedway (Jul 22, 2026)",
          "total": 122,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Richmond Raceway (Aug 5, 2026)",
          "total": 110,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ]
        }
      ],
      "rank": 2
    },
    {
      "name": "Bhark24",
      "score": 403,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 91,
          "picks": [
            "BRET GUZIK",
            "DYLAN MCDONALD",
            "JONATHON PLATT",
            "SCOTT SANDERSON"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 64,
          "picks": [
            "NICK NICKERSON",
            "SCOTT SANDERSON",
            "EDDIE HAGIGH",
            "BRANDON JACKSON"
          ]
        },
        {
          "race": "Nashville Superspeedway (Jul 22, 2026)",
          "total": 97,
          "picks": [
            "SCOTT SANDERSON",
            "GARRET BOBO",
            "EDDIE HAGIGH",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Pocono Raceway (Jul 29, 2026)",
          "total": 69,
          "picks": [
            "SCOTT SANDERSON",
            "GARRET BOBO",
            "EDDIE HAGIGH",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Richmond Raceway (Aug 5, 2026)",
          "total": 82,
          "picks": [
            "ADAM TAHAN",
            "BOB BERRY",
            "DYLAN MCDONALD",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 3
    },
    {
      "name": "Matt Crockett",
      "score": 311,
      "wins": 1,
      "wins_list": [
        "Richmond Raceway"
      ],
      "history": [
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 108,
          "picks": [
            "BENJAMIN LACY",
            "BOB BERRY",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ]
        },
        {
          "race": "Pocono Raceway (Jul 29, 2026)",
          "total": 85,
          "picks": [
            "ETHAN SIKORSKI",
            "BENJAMIN LACY",
            "MATT CROCKETT",
            "MICHAEL RAMOS"
          ]
        },
        {
          "race": "Richmond Raceway (Aug 5, 2026)",
          "total": 118,
          "picks": [
            "ETHAN SIKORSKI",
            "BENJAMIN LACY",
            "JONATHON PLATT",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 4
    },
    {
      "name": "Bobo",
      "score": 277,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 93,
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "ETHAN SIKORSKI",
            "KEVIN FOSTER"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 95,
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "CORDELL MCFARLIN",
            "JOSH ADAMS"
          ]
        },
        {
          "race": "Richmond Raceway (Aug 5, 2026)",
          "total": 89,
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "ETHAN SIKORSKI",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 5
    },
    {
      "name": "Michael Rakes",
      "score": 231,
      "wins": 1,
      "wins_list": [
        "Nashville"
      ],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 0,
          "picks": [
            "",
            "",
            "",
            ""
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 107,
          "picks": [
            "NICK NICKERSON",
            "JOSH ADAMS",
            "JONATHON PLATT",
            "BENJAMIN LACY"
          ]
        },
        {
          "race": "Nashville Superspeedway (Jul 22, 2026)",
          "total": 124,
          "picks": [
            "JONATHON PLATT",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "SCOTT SANDERSON"
          ]
        }
      ],
      "rank": 6
    },
    {
      "name": "cmac",
      "score": 230,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 66,
          "picks": [
            "JACKSON DUKE",
            "GARRET BOBO",
            "MARK GALLOWAY",
            "CORDELL MCFARLIN"
          ]
        },
        {
          "race": "Pocono Raceway (Jul 29, 2026)",
          "total": 93,
          "picks": [
            "CORDELL MCFARLIN",
            "GARRET BOBO",
            "JACKSON DUKE",
            "NICK NICKERSON"
          ]
        },
        {
          "race": "Richmond Raceway (Aug 5, 2026)",
          "total": 71,
          "picks": [
            "JACKSON DUKE",
            "GARRET BOBO",
            "CORDELL MCFARLIN",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 7
    },
    {
      "name": "robin allens bigest fan",
      "score": 116,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 116,
          "picks": [
            "NICK NICKERSON",
            "BENJAMIN LACY",
            "SCOTT SANDERSON",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 8
    },
    {
      "name": "LacyB",
      "score": 101,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 101,
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "KEVIN FOSTER",
            "NICK NICKERSON"
          ]
        }
      ],
      "rank": 9
    },
    {
      "name": "Ramos",
      "score": 87,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 87,
          "picks": [
            "BENJAMIN LACY",
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "NICK NICKERSON"
          ]
        }
      ],
      "rank": 10
    },
    {
      "name": "CHI3F",
      "score": 77,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 77,
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "NICK NICKERSON",
            "CURTIS YANCEY"
          ]
        }
      ],
      "rank": 11
    },
    {
      "name": "John Smith",
      "score": 76,
      "wins": 1,
      "wins_list": [
        "Daytona"
      ],
      "history": [
        {
          "race": "Daytona International Speedway (Jun 17, 2026)",
          "total": 76,
          "picks": [
            "Benjamin Lacy",
            "Jackson Knaak",
            "Josh Adams",
            "Curtis Yancey"
          ]
        }
      ],
      "rank": 12
    },
    {
      "name": "Jason Allegrini",
      "score": 69,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Nashville Superspeedway (Jul 22, 2026)",
          "total": 69,
          "picks": [
            "KEVIN FOSTER",
            "DYLAN MCDONALD",
            "JONATHON PLATT",
            "BENJAMIN LACY"
          ]
        }
      ],
      "rank": 13
    },
    {
      "name": "LateModelLover",
      "score": 66,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Daytona International Speedway (Jun 17, 2026)",
          "total": 66,
          "picks": [
            "Jonathon Platt",
            "Sean Britt",
            "Matt Crockett",
            "Curtis Yancey"
          ]
        }
      ],
      "rank": 14
    },
    {
      "name": "RaceFan99",
      "score": 17,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Daytona International Speedway (Jun 17, 2026)",
          "total": 17,
          "picks": [
            "Nick Nickerson",
            "Bill Harkins",
            "Nicole Kriesel",
            "Nolan Gross"
          ]
        }
      ],
      "rank": 15
    },
    {
      "name": "Sean Britt",
      "score": 0,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 0,
          "picks": [
            "",
            "",
            "",
            ""
          ]
        }
      ],
      "rank": 16
    },
    {
      "name": "Eddie Hagigh",
      "score": 0,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 0,
          "picks": [
            "",
            "",
            "",
            ""
          ]
        }
      ],
      "rank": 17
    }
  ],
  "races": [
    {
      "race": "Daytona International Speedway (Jun 17, 2026)",
      "track": "Daytona International Speedway",
      "date": "Jun 17, 2026",
      "caution_laps": 34,
      "winner": "John Smith",
      "results": [
        {
          "name": "John Smith",
          "picks": [
            "Benjamin Lacy",
            "Jackson Knaak",
            "Josh Adams",
            "Curtis Yancey"
          ],
          "total": 76
        },
        {
          "name": "LateModelLover",
          "picks": [
            "Jonathon Platt",
            "Sean Britt",
            "Matt Crockett",
            "Curtis Yancey"
          ],
          "total": 66
        },
        {
          "name": "RaceFan99",
          "picks": [
            "Nick Nickerson",
            "Bill Harkins",
            "Nicole Kriesel",
            "Nolan Gross"
          ],
          "total": 17
        }
      ]
    },
    {
      "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
      "track": "EchoPark Speedway (Atlanta)",
      "date": "Jun 24, 2026",
      "caution_laps": 24,
      "winner": "Bob Berry, Rebekah Weaver",
      "results": [
        {
          "name": "Bob Berry",
          "picks": [
            "BOB BERRY",
            "BENJAMIN LACY",
            "CONNOR GIBSON",
            "ETHAN SIKORSKI"
          ],
          "total": 101
        },
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ],
          "total": 101
        },
        {
          "name": "Bobo",
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "ETHAN SIKORSKI",
            "KEVIN FOSTER"
          ],
          "total": 93
        },
        {
          "name": "Bhark24",
          "picks": [
            "BRET GUZIK",
            "DYLAN MCDONALD",
            "JONATHON PLATT",
            "SCOTT SANDERSON"
          ],
          "total": 91
        },
        {
          "name": "Sean Britt",
          "picks": [
            "",
            "",
            "",
            ""
          ],
          "total": 0
        },
        {
          "name": "Eddie Hagigh",
          "picks": [
            "",
            "",
            "",
            ""
          ],
          "total": 0
        },
        {
          "name": "Michael Rakes",
          "picks": [
            "",
            "",
            "",
            ""
          ],
          "total": 0
        }
      ]
    },
    {
      "race": "Charlotte Motor Speedway (Jul 8, 2026)",
      "track": "Charlotte Motor Speedway",
      "date": "Jul 8, 2026",
      "caution_laps": 30,
      "winner": "Bob Berry",
      "results": [
        {
          "name": "Bob Berry",
          "picks": [
            "BENJAMIN LACY",
            "JONATHON PLATT",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ],
          "total": 121
        },
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ],
          "total": 120
        },
        {
          "name": "LacyB",
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "KEVIN FOSTER",
            "NICK NICKERSON"
          ],
          "total": 101
        },
        {
          "name": "Ramos",
          "picks": [
            "BENJAMIN LACY",
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "NICK NICKERSON"
          ],
          "total": 87
        },
        {
          "name": "CHI3F",
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "NICK NICKERSON",
            "CURTIS YANCEY"
          ],
          "total": 77
        }
      ]
    },
    {
      "race": "Bristol Motor Speedway (Jul 15, 2026)",
      "track": "Bristol Motor Speedway",
      "date": "Jul 15, 2026",
      "caution_laps": 93,
      "winner": "Bob Berry",
      "results": [
        {
          "name": "bhark24",
          "picks": [
            "NICK NICKERSON",
            "SCOTT SANDERSON",
            "EDDIE HAGIGH",
            "BRANDON JACKSON"
          ],
          "total": 64
        },
        {
          "name": "cmac",
          "picks": [
            "JACKSON DUKE",
            "GARRET BOBO",
            "MARK GALLOWAY",
            "CORDELL MCFARLIN"
          ],
          "total": 66
        },
        {
          "name": "Bobo",
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "CORDELL MCFARLIN",
            "JOSH ADAMS"
          ],
          "total": 95
        },
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ],
          "total": 96
        },
        {
          "name": "robin allens bigest fan",
          "picks": [
            "NICK NICKERSON",
            "BENJAMIN LACY",
            "SCOTT SANDERSON",
            "KEVIN FOSTER"
          ],
          "total": 116
        },
        {
          "name": "Michael rakes",
          "picks": [
            "NICK NICKERSON",
            "JOSH ADAMS",
            "JONATHON PLATT",
            "BENJAMIN LACY"
          ],
          "total": 107
        },
        {
          "name": "Matt Crockett",
          "picks": [
            "BENJAMIN LACY",
            "BOB BERRY",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ],
          "total": 108
        },
        {
          "name": "Bob Berry",
          "picks": [
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "BENJAMIN LACY",
            "BOB BERRY"
          ],
          "total": 126
        }
      ]
    },
    {
      "race": "Nashville Superspeedway (Jul 22, 2026)",
      "track": "Nashville Superspeedway",
      "date": "Jul 22, 2026",
      "caution_laps": 30,
      "winner": "Michael Rakes",
      "results": [
        {
          "name": "Jason Allegrini",
          "picks": [
            "KEVIN FOSTER",
            "DYLAN MCDONALD",
            "JONATHON PLATT",
            "BENJAMIN LACY"
          ],
          "total": 69
        },
        {
          "name": "Bhark24",
          "picks": [
            "SCOTT SANDERSON",
            "GARRET BOBO",
            "EDDIE HAGIGH",
            "JONATHON PLATT"
          ],
          "total": 97
        },
        {
          "name": "Michael Rakes",
          "picks": [
            "JONATHON PLATT",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "SCOTT SANDERSON"
          ],
          "total": 124
        },
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ],
          "total": 122
        }
      ]
    },
    {
      "race": "Pocono Raceway (Jul 29, 2026)",
      "track": "Pocono Raceway",
      "date": "Jul 29, 2026",
      "caution_laps": 42,
      "winner": "Bob Berry",
      "results": [
        {
          "name": "Bhark24",
          "picks": [
            "SCOTT SANDERSON",
            "GARRET BOBO",
            "EDDIE HAGIGH",
            "JONATHON PLATT"
          ],
          "total": 69
        },
        {
          "name": "cmac",
          "picks": [
            "CORDELL MCFARLIN",
            "GARRET BOBO",
            "JACKSON DUKE",
            "NICK NICKERSON"
          ],
          "total": 93
        },
        {
          "name": "Bob Berry",
          "picks": [
            "ADAM TAHAN",
            "MICHAEL RAMOS",
            "SCOTT SANDERSON",
            "NICK NICKERSON"
          ],
          "total": 126
        },
        {
          "name": "Matt Crockett",
          "picks": [
            "ETHAN SIKORSKI",
            "BENJAMIN LACY",
            "MATT CROCKETT",
            "MICHAEL RAMOS"
          ],
          "total": 85
        }
      ]
    },
    {
      "race": "Richmond Raceway (Aug 5, 2026)",
      "track": "Richmond Raceway",
      "date": "Aug 5, 2026",
      "caution_laps": 44,
      "winner": "Matt Crockett",
      "results": [
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ],
          "total": 110
        },
        {
          "name": "cmac",
          "picks": [
            "JACKSON DUKE",
            "GARRET BOBO",
            "CORDELL MCFARLIN",
            "KEVIN FOSTER"
          ],
          "total": 71
        },
        {
          "name": "Bobo",
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "ETHAN SIKORSKI",
            "KEVIN FOSTER"
          ],
          "total": 89
        },
        {
          "name": "Matt Crockett",
          "picks": [
            "ETHAN SIKORSKI",
            "BENJAMIN LACY",
            "JONATHON PLATT",
            "KEVIN FOSTER"
          ],
          "total": 118
        },
        {
          "name": "Bob Berry",
          "picks": [
            "ADAM TAHAN",
            "JONATHON PLATT",
            "SCOTT SANDERSON",
            "KEVIN FOSTER"
          ],
          "total": 114
        },
        {
          "name": "Bhark24",
          "picks": [
            "ADAM TAHAN",
            "BOB BERRY",
            "DYLAN MCDONALD",
            "KEVIN FOSTER"
          ],
          "total": 82
        }
      ]
    }
  ]
};
