// Automatically generated by update_fantasy.py. Do not edit directly.
const fantasyData = {
  "last_updated": "2026-07-15 23:22:42",
  "latest_race": {
    "track": "Bristol Motor Speedway",
    "date": "Jul 15, 2026",
    "caution_laps": 93,
    "winner": "Bob Berry (126 pts)",
    "driver_scores": {
      "benjamin lacy": {
        "driver_name": "lacy, benjamin",
        "finish": 1,
        "start": 13,
        "incidents": 0,
        "status": "Running",
        "base_points": 40,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 3,
        "dnf_penalty": 0,
        "total_points": 43
      },
      "scott sanderson": {
        "driver_name": "sanderson, scott",
        "finish": 2,
        "start": 2,
        "incidents": 8,
        "status": "Running",
        "base_points": 35,
        "pole_bonus": 0,
        "most_laps_led_bonus": 5,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 40
      },
      "dylan mcdonald": {
        "driver_name": "mcdonald3, dylan",
        "finish": 3,
        "start": 23,
        "incidents": 20,
        "status": "Running",
        "base_points": 34,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 34
      },
      "johnathon platt": {
        "driver_name": "platt, johnathon",
        "finish": 4,
        "start": 31,
        "incidents": 24,
        "status": "Running",
        "base_points": 33,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 33
      },
      "kevin foster": {
        "driver_name": "foster, kevin",
        "finish": 5,
        "start": 4,
        "incidents": 12,
        "status": "Running",
        "base_points": 32,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 32
      },
      "reagan fruge": {
        "driver_name": "fruge, reagan",
        "finish": 6,
        "start": 5,
        "incidents": 30,
        "status": "Running",
        "base_points": 31,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 31
      },
      "connor gibson": {
        "driver_name": "gibson, connor",
        "finish": 7,
        "start": 11,
        "incidents": 40,
        "status": "Running",
        "base_points": 30,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 30
      },
      "curtis yancey": {
        "driver_name": "yancey, curtis",
        "finish": 8,
        "start": 3,
        "incidents": 32,
        "status": "Running",
        "base_points": 29,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 29
      },
      "jackson duke": {
        "driver_name": "duke, jackson",
        "finish": 9,
        "start": 20,
        "incidents": 16,
        "status": "Running",
        "base_points": 28,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 28
      },
      "chad hartle": {
        "driver_name": "hartle, chad",
        "finish": 10,
        "start": 29,
        "incidents": 18,
        "status": "Running",
        "base_points": 27,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 27
      },
      "garret bobo": {
        "driver_name": "bobo, garret",
        "finish": 11,
        "start": 8,
        "incidents": 26,
        "status": "Running",
        "base_points": 26,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 26
      },
      "joshua adams": {
        "driver_name": "adams, joshua",
        "finish": 12,
        "start": 1,
        "incidents": 28,
        "status": "Running",
        "base_points": 25,
        "pole_bonus": 5,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 30
      },
      "michael rakes": {
        "driver_name": "rakes, michael",
        "finish": 13,
        "start": 17,
        "incidents": 20,
        "status": "Running",
        "base_points": 24,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 24
      },
      "ethan sikorski": {
        "driver_name": "sikorski, ethan",
        "finish": 14,
        "start": 6,
        "incidents": 28,
        "status": "Running",
        "base_points": 23,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 23
      },
      "david leakey": {
        "driver_name": "leakey, david",
        "finish": 15,
        "start": 7,
        "incidents": 34,
        "status": "Running",
        "base_points": 22,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 22
      },
      "bob berry": {
        "driver_name": "berry, bob",
        "finish": 16,
        "start": 14,
        "incidents": 20,
        "status": "Running",
        "base_points": 21,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 21
      },
      "joshua billiter": {
        "driver_name": "billiter, joshua",
        "finish": 17,
        "start": 15,
        "incidents": 24,
        "status": "Running",
        "base_points": 20,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 20
      },
      "eddie hagigh": {
        "driver_name": "hagigh, eddie",
        "finish": 18,
        "start": 22,
        "incidents": 12,
        "status": "Running",
        "base_points": 19,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 19
      },
      "ty corino": {
        "driver_name": "corino, ty",
        "finish": 19,
        "start": 34,
        "incidents": 32,
        "status": "Running",
        "base_points": 18,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 18
      },
      "davis carroll": {
        "driver_name": "carroll, davis",
        "finish": 20,
        "start": 12,
        "incidents": 30,
        "status": "Running",
        "base_points": 17,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 17
      },
      "nathan santos": {
        "driver_name": "santos2, nathan",
        "finish": 21,
        "start": 16,
        "incidents": 28,
        "status": "Running",
        "base_points": 16,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 16
      },
      "bill harkins": {
        "driver_name": "harkins, bill",
        "finish": 22,
        "start": 27,
        "incidents": 42,
        "status": "Running",
        "base_points": 15,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 15
      },
      "logan murray": {
        "driver_name": "murray, logan",
        "finish": 23,
        "start": 9,
        "incidents": 8,
        "status": "Disconnected",
        "base_points": 14,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 14
      },
      "matt crockett": {
        "driver_name": "crockett, matt",
        "finish": 24,
        "start": 25,
        "incidents": 24,
        "status": "Running",
        "base_points": 13,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 13
      },
      "john osborne": {
        "driver_name": "osborne, jon",
        "finish": 25,
        "start": 28,
        "incidents": 16,
        "status": "Disconnected",
        "base_points": 12,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 12
      },
      "cordell mcfarlin": {
        "driver_name": "mcfarlin, cordell",
        "finish": 26,
        "start": 30,
        "incidents": 32,
        "status": "Disconnected",
        "base_points": 11,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 11
      },
      "jason greenwell": {
        "driver_name": "greenwell, jason",
        "finish": 27,
        "start": 18,
        "incidents": 22,
        "status": "Disconnected",
        "base_points": 10,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 10
      },
      "victor weaver": {
        "driver_name": "weaver, victor",
        "finish": 28,
        "start": 35,
        "incidents": 14,
        "status": "Disconnected",
        "base_points": 9,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 9
      },
      "tre ellis": {
        "driver_name": "ellis, tre",
        "finish": 29,
        "start": 24,
        "incidents": 28,
        "status": "Disconnected",
        "base_points": 8,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 8
      },
      "carter phillips": {
        "driver_name": "phillips, carter",
        "finish": 30,
        "start": 19,
        "incidents": 10,
        "status": "Disconnected",
        "base_points": 7,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 7
      },
      "ricky hart jr": {
        "driver_name": "hart jr, ricky",
        "finish": 31,
        "start": 33,
        "incidents": 16,
        "status": "Running",
        "base_points": 6,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 6
      },
      "bret guzik": {
        "driver_name": "guzik, bret",
        "finish": 32,
        "start": 21,
        "incidents": 10,
        "status": "Disconnected",
        "base_points": 5,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 5
      },
      "brandon jackson": {
        "driver_name": "jackson, brandon",
        "finish": 33,
        "start": 10,
        "incidents": 12,
        "status": "Disconnected",
        "base_points": 4,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 4
      },
      "jason allegrini": {
        "driver_name": "allegrini, jason",
        "finish": 34,
        "start": 26,
        "incidents": 4,
        "status": "Disconnected",
        "base_points": 3,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 3
      },
      "terry kondas": {
        "driver_name": "kondas, terry",
        "finish": 35,
        "start": 32,
        "incidents": 4,
        "status": "Disconnected",
        "base_points": 2,
        "pole_bonus": 0,
        "most_laps_led_bonus": 0,
        "clean_race_bonus": 0,
        "dnf_penalty": 0,
        "total_points": 2
      }
    }
  },
  "tiers": {
    "A": [
      "NICK NICKERSON",
      "JONATHON PLATT",
      "KEVIN FOSTER",
      "DAVID LEAKEY",
      "LOGAN MURRAY",
      "BENJAMIN LACY",
      "RICKY HART",
      "BRET GUZIK"
    ],
    "B": [
      "BILL HARKINS",
      "NICOLE KRIESEL",
      "SEAN BRITT",
      "JASON ALLEGRINI",
      "MATT CROCKETT",
      "JOSH ADAMS",
      "JOSHUA ADAMS",
      "MICHAEL RAMOS",
      "TY CORINO",
      "TYSON KOPF",
      "BOB BERRY",
      "JASON GREENWELL",
      "JOSH BILLITER",
      "JOSHUA BILLITER",
      "JACKSON KNAAK"
    ],
    "C": [
      "DIONTE RADER",
      "DIANTE RODER",
      "MATT BAILEY",
      "NATHAN SANTOS",
      "DYLAN NICASTRO",
      "ETHAN SIKORSKI",
      "REAGAN FRUGE",
      "CHAD HARTLE",
      "MICHAEL RAKES",
      "CURTIS YANCEY",
      "BRANDON GEERS",
      "MARK ALAN BIVENS",
      "DAVID WESTOVER JR",
      "BRANDON JACKSON",
      "EDDIE HAGIGH",
      "NOLAN GROSS",
      "DAVIS CARROLL",
      "LUCAS WILSON",
      "DYLAN MCDONALD",
      "WES FULLER",
      "RICKY GONZALES"
    ]
  },
  "recap_story": {
    "race_key": "Bristol Motor Speedway (Jul 15, 2026)",
    "title": "Bob Berry Wins at Bristol Motor Speedway!",
    "date": "July 15, 2026",
    "content": "A fantastic week of racing at Bristol Motor Speedway saw Bob Berry claim the weekly fantasy victory with a score of 126 points! The race ran with 93 caution laps, which resolved any scoring ties using caution lap tiebreaker guesses. Check back soon for the full weekly results and roster breakdowns!"
  },
  "leaderboard": [
    {
      "name": "Bob Berry",
      "score": 348,
      "wins": 3,
      "wins_list": [
        "Atlanta",
        "Charlotte",
        "Bristol"
      ],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 101,
          "picks": [
            "BOB BERRY",
            "BENJAMIN LACY",
            "CONNOR GIBSON",
            "ETHAN SIKORSKI"
          ]
        },
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 121,
          "picks": [
            "BENJAMIN LACY",
            "JONATHON PLATT",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 126,
          "picks": [
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "BENJAMIN LACY",
            "BOB BERRY"
          ]
        }
      ],
      "rank": 1
    },
    {
      "name": "Rebekah Weaver",
      "score": 317,
      "wins": 1,
      "wins_list": [
        "Atlanta"
      ],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 101,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 120,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 96,
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ]
        }
      ],
      "rank": 2
    },
    {
      "name": "Bobo",
      "score": 188,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 93,
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "ETHAN SIKORSKI",
            "KEVIN FOSTER"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 95,
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "CORDELL MCFARLIN",
            "JOSH ADAMS"
          ]
        }
      ],
      "rank": 3
    },
    {
      "name": "Bhark24",
      "score": 155,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 91,
          "picks": [
            "BRET GUZIK",
            "DYLAN MCDONALD",
            "JONATHON PLATT",
            "SCOTT SANDERSON"
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 64,
          "picks": [
            "NICK NICKERSON",
            "SCOTT SANDERSON",
            "EDDIE HAGIGH",
            "BRANDON JACKSON"
          ]
        }
      ],
      "rank": 4
    },
    {
      "name": "robin allens bigest fan",
      "score": 116,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 116,
          "picks": [
            "NICK NICKERSON",
            "BENJAMIN LACY",
            "SCOTT SANDERSON",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 5
    },
    {
      "name": "Matt Crockett",
      "score": 108,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 108,
          "picks": [
            "BENJAMIN LACY",
            "BOB BERRY",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ]
        }
      ],
      "rank": 6
    },
    {
      "name": "Michael Rakes",
      "score": 107,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 0,
          "picks": [
            "",
            "",
            "",
            ""
          ]
        },
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 107,
          "picks": [
            "NICK NICKERSON",
            "JOSH ADAMS",
            "JONATHON PLATT",
            "BENJAMIN LACY"
          ]
        }
      ],
      "rank": 7
    },
    {
      "name": "LacyB",
      "score": 101,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 101,
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "KEVIN FOSTER",
            "NICK NICKERSON"
          ]
        }
      ],
      "rank": 8
    },
    {
      "name": "Ramos",
      "score": 87,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 87,
          "picks": [
            "BENJAMIN LACY",
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "NICK NICKERSON"
          ]
        }
      ],
      "rank": 9
    },
    {
      "name": "CHI3F",
      "score": 77,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Charlotte Motor Speedway (Jul 8, 2026)",
          "total": 77,
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "NICK NICKERSON",
            "CURTIS YANCEY"
          ]
        }
      ],
      "rank": 10
    },
    {
      "name": "John Smith",
      "score": 76,
      "wins": 1,
      "wins_list": [
        "Daytona"
      ],
      "history": [
        {
          "race": "Daytona International Speedway (Jun 17, 2026)",
          "total": 76,
          "picks": [
            "Benjamin Lacy",
            "Jackson Knaak",
            "Josh Adams",
            "Curtis Yancey"
          ]
        }
      ],
      "rank": 11
    },
    {
      "name": "LateModelLover",
      "score": 66,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Daytona International Speedway (Jun 17, 2026)",
          "total": 66,
          "picks": [
            "Jonathon Platt",
            "Sean Britt",
            "Matt Crockett",
            "Curtis Yancey"
          ]
        }
      ],
      "rank": 12
    },
    {
      "name": "cmac",
      "score": 66,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Bristol Motor Speedway (Jul 15, 2026)",
          "total": 66,
          "picks": [
            "JACKSON DUKE",
            "GARRET BOBO",
            "MARK GALLOWAY",
            "CORDELL MCFARLIN"
          ]
        }
      ],
      "rank": 13
    },
    {
      "name": "RaceFan99",
      "score": 17,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "Daytona International Speedway (Jun 17, 2026)",
          "total": 17,
          "picks": [
            "Nick Nickerson",
            "Bill Harkins",
            "Nicole Kriesel",
            "Nolan Gross"
          ]
        }
      ],
      "rank": 14
    },
    {
      "name": "Sean Britt",
      "score": 0,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 0,
          "picks": [
            "",
            "",
            "",
            ""
          ]
        }
      ],
      "rank": 15
    },
    {
      "name": "Eddie Hagigh",
      "score": 0,
      "wins": 0,
      "wins_list": [],
      "history": [
        {
          "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
          "total": 0,
          "picks": [
            "",
            "",
            "",
            ""
          ]
        }
      ],
      "rank": 16
    }
  ],
  "races": [
    {
      "race": "Daytona International Speedway (Jun 17, 2026)",
      "track": "Daytona International Speedway",
      "date": "Jun 17, 2026",
      "caution_laps": 34,
      "winner": "John Smith",
      "results": [
        {
          "name": "John Smith",
          "picks": [
            "Benjamin Lacy",
            "Jackson Knaak",
            "Josh Adams",
            "Curtis Yancey"
          ],
          "total": 76
        },
        {
          "name": "LateModelLover",
          "picks": [
            "Jonathon Platt",
            "Sean Britt",
            "Matt Crockett",
            "Curtis Yancey"
          ],
          "total": 66
        },
        {
          "name": "RaceFan99",
          "picks": [
            "Nick Nickerson",
            "Bill Harkins",
            "Nicole Kriesel",
            "Nolan Gross"
          ],
          "total": 17
        }
      ]
    },
    {
      "race": "EchoPark Speedway (Atlanta) (Jun 24, 2026)",
      "track": "EchoPark Speedway (Atlanta)",
      "date": "Jun 24, 2026",
      "caution_laps": 24,
      "winner": "Bob Berry, Rebekah Weaver",
      "results": [
        {
          "name": "Bob Berry",
          "picks": [
            "BOB BERRY",
            "BENJAMIN LACY",
            "CONNOR GIBSON",
            "ETHAN SIKORSKI"
          ],
          "total": 101
        },
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ],
          "total": 101
        },
        {
          "name": "Bobo",
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "ETHAN SIKORSKI",
            "KEVIN FOSTER"
          ],
          "total": 93
        },
        {
          "name": "Bhark24",
          "picks": [
            "BRET GUZIK",
            "DYLAN MCDONALD",
            "JONATHON PLATT",
            "SCOTT SANDERSON"
          ],
          "total": 91
        },
        {
          "name": "Sean Britt",
          "picks": [
            "",
            "",
            "",
            ""
          ],
          "total": 0
        },
        {
          "name": "Eddie Hagigh",
          "picks": [
            "",
            "",
            "",
            ""
          ],
          "total": 0
        },
        {
          "name": "Michael Rakes",
          "picks": [
            "",
            "",
            "",
            ""
          ],
          "total": 0
        }
      ]
    },
    {
      "race": "Charlotte Motor Speedway (Jul 8, 2026)",
      "track": "Charlotte Motor Speedway",
      "date": "Jul 8, 2026",
      "caution_laps": 30,
      "winner": "Bob Berry",
      "results": [
        {
          "name": "Bob Berry",
          "picks": [
            "BENJAMIN LACY",
            "JONATHON PLATT",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ],
          "total": 121
        },
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "NICK NICKERSON",
            "JONATHON PLATT"
          ],
          "total": 120
        },
        {
          "name": "LacyB",
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "KEVIN FOSTER",
            "NICK NICKERSON"
          ],
          "total": 101
        },
        {
          "name": "Ramos",
          "picks": [
            "BENJAMIN LACY",
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "NICK NICKERSON"
          ],
          "total": 87
        },
        {
          "name": "CHI3F",
          "picks": [
            "BENJAMIN LACY",
            "MICHAEL RAMOS",
            "NICK NICKERSON",
            "CURTIS YANCEY"
          ],
          "total": 77
        }
      ]
    },
    {
      "race": "Bristol Motor Speedway (Jul 15, 2026)",
      "track": "Bristol Motor Speedway",
      "date": "Jul 15, 2026",
      "caution_laps": 93,
      "winner": "Bob Berry",
      "results": [
        {
          "name": "bhark24",
          "picks": [
            "NICK NICKERSON",
            "SCOTT SANDERSON",
            "EDDIE HAGIGH",
            "BRANDON JACKSON"
          ],
          "total": 64
        },
        {
          "name": "cmac",
          "picks": [
            "JACKSON DUKE",
            "GARRET BOBO",
            "MARK GALLOWAY",
            "CORDELL MCFARLIN"
          ],
          "total": 66
        },
        {
          "name": "Bobo",
          "picks": [
            "GARRET BOBO",
            "JACKSON DUKE",
            "CORDELL MCFARLIN",
            "JOSH ADAMS"
          ],
          "total": 95
        },
        {
          "name": "Rebekah Weaver",
          "picks": [
            "VICTOR WEAVER",
            "JOSH ADAMS",
            "MICHAEL RAKES",
            "JONATHON PLATT"
          ],
          "total": 96
        },
        {
          "name": "robin allens bigest fan",
          "picks": [
            "NICK NICKERSON",
            "BENJAMIN LACY",
            "SCOTT SANDERSON",
            "KEVIN FOSTER"
          ],
          "total": 116
        },
        {
          "name": "Michael rakes",
          "picks": [
            "NICK NICKERSON",
            "JOSH ADAMS",
            "JONATHON PLATT",
            "BENJAMIN LACY"
          ],
          "total": 107
        },
        {
          "name": "Matt Crockett",
          "picks": [
            "BENJAMIN LACY",
            "BOB BERRY",
            "JON OSBORNE",
            "KEVIN FOSTER"
          ],
          "total": 108
        },
        {
          "name": "Bob Berry",
          "picks": [
            "CURTIS YANCEY",
            "JONATHON PLATT",
            "BENJAMIN LACY",
            "BOB BERRY"
          ],
          "total": 126
        }
      ]
    }
  ]
};
